### PR TITLE
add max-width of 100% for the resize-sensor element 

### LINKED ISSUE #232: resize-sensor wider than the view port
Hi, I've encountered a situation where the `.resize-sensor` element is wider than the  view port thus enforcing a horizontal scroll-bar.   
My fix was to just add the rule: 
```
.resize-sensor{
  max-width:  100%;
}
```

Maybe this should be added to the source code.

### PR DESCRIPTION
**Pull request by sag1v**
should fix #232

### CODE REVIEW

**Comment by marcj** [comment]
Thanks!

**Comment by sag1v** [comment]
@marcj No problem.
This is strange though, have you change the `resizeSensor` behavior lately? because i don't see the new element with the `.resize-sensor` class being added to the `DOM`  anymore, though everything looks like its working fine.  

Tested it with older version and i do see the element being added.

**Comment by sag1v** [comment]
@marcj Ok i think i got an answer for my question, with [this line](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js#L245).

So we are now using the `ResizeObserver` so no need to append our own element. 
On what situations the ResizeObserver wont be available? 
` if (typeof ResizeObserver !== "undefined") { ...`

**Comment by marcj** [comment]
ResizeObserver is new Chrome only

**Comment by sag1v** [comment]
@marcj Thanks! yeah just found it :)
https://caniuse.com/#feat=resizeobserver

**Pull request merged**
