### PR TITLE
Handle display:none gracefully on element or its parents

### PR DESCRIPTION
**Pull request by jsdw**
This commit adds checking to the element and its parents in which elements-to-be-checked are queued and their computed display properties checked under a single interval loop, which will trigger a reset() call to the resize handlers when the first instance of no display:nones becomes true.

I moved some code about to make this easier (reused the EventQueue), and made this interval checking optional, so it will only be used if you ask for it. Otherwise, a hook is provided so that you an manually run the check; this can be tied in with eg Angulars $digest mechanism

### CODE REVIEW

**Comment by marcj** [comment]
Looks promising. Can you describe in your own words what the code workflow is when places a resize-sensor to a element that is not visible? :)

**Comment by jsdw** [comment]
Sure! The following new stuff takes place when a user adds a resize sensor to `el`:

1. Get all ancestors to `el` and add them, and `el` to an array `elArr`
2. Add all of the elements in `elArr` to the list of elements to be monitored (ignoring any that already exist there).
3. Add a callback to an EventQueue which iterates over each el looking at a cached display boolean (see step 4). if no elements are "display:none", cleanup monitoring and fire a callback which triggers a reset() call, to properly set up the resize scrollbars, now it is possible to do so.
4. If we have asked for interval checking, and it is not already running, kick off a function which fires every 150ms and:
  - gets computed display style for each element we have been asked to monitor
  - appends bool to each el denoting whether "display:none" was seen.
  - fires off each callback on the EventQueue (see step 3).
  - disables itself if there are no longer any elements to monitor.

Whether to actually fire off the interval in step 4 is optional; I have also added a call from the instantiated ResizeSensor which allows you to trigger a check manually. This is incase all sources of CSS manipulations are known (eg they all come through Angular) and so you'd rather hook into that than use an interval.

It's worth having a more thorough look since there is more code here, and in addition you may decide to change the additional bool I passed to ResizeSensor to control the use of interval into perhaps a more general "options" hash, which might allow you to avoid monitoring entirely as well as just avoid the interval part of it (I didn't bother since I don't think it adds much overhead without the interval).

The general hope is that, while this code does add an interval, it doesn't need to be super frequent (unlike one on a resize would be), can be disabled, and under all cases in which this library worked off the bat, would barely be noticed anyway.

**Comment by marcj** [comment]
I see, thank! Maybe we could use a animation hack to check if a element becomes visible. https://twitter.com/derSchepp/status/725445055897583616 So we don't need that timer (which makes things slow I guess when having a lot of resize-sensor items in the DOM)

**Comment by jsdw** [comment]
That's an interesting idea! Should be quite easy to re-jig my code to do that - the per-element setup will just add a keyframe animation to the element, the event attached would fire the callbacks in the EventQueue, and the cleanup would remove the keyframe lark/event. I'll have a play when I have a little free time.

**Comment by marcj** [comment]
Awesome! If you need help feel free to contact me ([Gitter](https://gitter.im/marcj/css-element-queries?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)) 👍

**Comment by jsdw** [comment]
Thanks, I'm quite busy at the moment so if you fancy having a shot at it,
please be my guest! Otherwise I'm sure I'll find some time eventually ☺

**Comment by marcj** [comment]
Closing for now, as we are working on the animation check. We're the high-speed element queries polyfill, thus we need to make sure we maintain max performance without using interval checks like in this PR. Thanks anyways!

**Pull request closed without merging**
