### PR TITLE
Use UMD module definition for increase compatibility.

### PR DESCRIPTION
**Pull request by josephschmitt**
Also makes importing of ResizeSensor work out of the box with jspm.

### CODE REVIEW

**Comment by marcj** [comment]
Nice work, LGTM, thanks! :)

**Comment by josephschmitt** [comment]
Awesome, thanks for the quick turnaround! Any chance you're planning a new release tag soon? Would love to get this version into our project via jspm.

**Comment by marcj** [comment]
Sure! just want to make some housekeeping first, then next version will be tagged 👍

**Comment by patrickmichalina** [comment]
Tagging soon? Would love to import this with JSPM

**Comment by onlywei** [comment]
Hello. Is this going to be tagged soon?

**Pull request merged**
