### PR TITLE
Allow users to choose which axis to be observed for resize events. (#…

### PR DESCRIPTION
**Pull request by newlukai**
…158)

### CODE REVIEW

**Comment by marcj** [comment]
Is there a reason why you would want that? I don't see any performance difference coming with this change.

**Comment by newlukai** [comment]
Currently I'm building a Polymer app displaying a dashboard containing several SVG graphics. One part of the UI is a sidebar (or drawer) which the user can display or hide. Displaying this sidebar should lead to reducing the width of the dashboard. After displaying the sidebar, I need to tell the SVG graphics that the width changed (which is why I use ResizeSensor).

In Firefox, this internal rearranging of those SVG graphics leads to an increase of the SVGs height. So, again a resize event is fired, which leads to rearranging the SVG graphics which leads to some pixels more in height, which leads to a resize event, ...
This loop stops once I reach the max-height of the SVG graphics.

I couldn't track down the reason for this behavior in Firefox. In Chrome it just works smoothly. Of course I could set a fixed height for the SVG graphics, but that's not what I wanted. So I decided to restrict the sensor to only the width.

**Comment by marcj** [comment]
I see. One question tho: Why don't you limit the detection on your own?

```javascript

var oldWidth;
new ResizeSensor($('#foo'), function() {
    if (oldWidth !== element.clientWidth){
        oldWidth = element.clientWidth;
        //do stuff only when width changed.
    }
});
```

I'd prefer this way as the proposed API with two additional argument seems not so sexy.

**Comment by newlukai** [comment]
Yep, this looks more sexy, you are right. Sometimes my thoughts are more Java oriented than optimized for JavaScript. I'm going to test this...

**Comment by newlukai** [comment]
Currently I'm building a Polymer app displaying a dashboard containing several SVG graphics. One part of the UI is a sidebar (or drawer) which the user can display or hide. Displaying this sidebar should lead to reducing the width of the dashboard. After displaying the sidebar, I need to tell the SVG graphics that the width changed (which is why I use ResizeSensor).

In Firefox, this internal rearranging of those SVG graphics leads to an increase of the SVGs height. So, again a resize event is fired, which leads to rearranging the SVG graphics which leads to some pixels more in height, which leads to a resize event, ...
This loop stops once I reach the max-height of the SVG graphics.

I couldn't track down the reason for this behavior in Firefox. In Chrome it just works smoothly. Of course I could set a fixed height for the SVG graphics, but that's not what I wanted. So I decided to restrict the sensor to only the width.

**Comment by newlukai** [comment]
Sorry for the delay. You solution works fine.

**Pull request closed without merging**
